// Converts the MIT-licensed YouTD 2 data tables in third_party/youtd2 into
// src/data/youtd/generated.js. Run: node tools/import-youtd2.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const DIR = new URL('../third_party/youtd2/', import.meta.url);
const OUT = new URL('../src/data/youtd/generated.js', import.meta.url);

function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') quoted = false;
      else field += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n' || ch === '\r') {
      if (ch === '\r' && text[i + 1] === '\n') i++;
      row.push(field); field = '';
      if (row.length > 1 || row[0] !== '') rows.push(row);
      row = [];
    } else field += ch;
  }
  if (field || row.length) { row.push(field); rows.push(row); }
  const [head, ...body] = rows;
  return body.map((r) => Object.fromEntries(head.map((h, i) => [h, r[i] ?? ''])));
}

const load = (name) => parseCsv(readFileSync(new URL(`${name}.csv`, DIR), 'utf8'));
const ids = (s) => (s ? s.split(',').map((x) => x.trim()).filter(Boolean) : []);
const num = (s, d = 0) => (s === '' || s == null ? d : Number(s));
const isEmptyScript = (p) => /empty_(tower|item)_behavior\.gd$/.test(p);
const scriptName = (p) => (p ? p.split('/').pop().replace('.gd', '') : '');

// "MOD_X,base,perLevel|MOD_Y,..." -> [[key, base, perLevel]]
const mods = (s) => (s ? s.split('|').filter(Boolean).map((part) => {
  const [key, base, add] = part.split(',');
  return [key, Number(base), Number(add || 0)];
}) : []);

const abilities = Object.fromEntries(load('ability_properties').map((a) => [a.id, { name: a['name_english'] || a['name english'], range: num(a.range) }]));
const auras = Object.fromEntries(load('aura_properties').map((a) => [a.id, {
  name: a.name_english, range: num(a.range), target: a.target_type, self: a.target_self === 'TRUE', level: num(a.level), levelAdd: num(a.level_add),
}]));
const autocasts = Object.fromEntries(load('autocast_properties').map((a) => [a.id, {
  name: a.name_english, type: a.autocast_type, cd: num(a.cooldown), mana: num(a.mana_cost), range: num(a.cast_range), autoRange: num(a.auto_range),
}]));

const towers = load('tower_properties').map((r) => {
  const splash = r['splash attack'] ? r['splash attack'].split(',').map(Number) : [];
  const rings = [];
  for (let i = 0; i + 1 < splash.length; i += 2) rings.push([splash[i], splash[i + 1]]);
  const bounce = r['bounce attack'] ? r['bounce attack'].split(',').map(Number) : null;
  return {
    id: num(r.id), name: r['name english'], family: num(r['family id']), tier: num(r.tier), author: r.author,
    rarity: r.rarity, element: r.element, attackEnabled: r['attack enabled'] === 'TRUE', attack: r['attack type'],
    range: num(r['attack range']), cd: num(r['attack cd']), dmg: [num(r['dmg min']), num(r['dmg max'])],
    mana: num(r.mana), manaRegen: num(r['mana regen']), cost: num(r.cost),
    missileSpeed: num(r['missile speed']), arc: num(r['missile arc']), lightning: r['missile uses lightning visual'] === 'TRUE',
    target: r.attack_target_type, multishot: num(r.multishot, 0), splash: rings, bounce,
    mods: mods(r.specials),
    abilities: ids(r['ability list']).map((id) => abilities[id]).filter(Boolean),
    auras: ids(r['aura list']).map((id) => auras[id]).filter(Boolean),
    autocasts: ids(r['autocast list']).map((id) => autocasts[id]).filter(Boolean),
    script: isEmptyScript(r['script path']) ? null : scriptName(r['script path']),
  };
});

const items = load('item_properties').map((r) => ({
  id: num(r.id), name: r['name english'], type: r.type, author: r.author, rarity: r.rarity, cost: num(r.cost),
  reqWave: num(r['required wave level']), mods: mods(r.specials),
  abilities: ids(r['ability list']).map((id) => abilities[id]).filter(Boolean),
  auras: ids(r['aura list']).map((id) => auras[id]).filter(Boolean),
  autocasts: ids(r['autocast list']).map((id) => autocasts[id]).filter(Boolean),
  script: isEmptyScript(r['script path']) ? null : scriptName(r['script path']),
}));

const header = `// GENERATED by tools/import-youtd2.mjs from third_party/youtd2 (MIT license). Do not edit.\n`;
writeFileSync(OUT, `${header}export const YT_TOWERS = ${JSON.stringify(towers)};\nexport const YT_ITEMS = ${JSON.stringify(items)};\n`);
console.log(`towers ${towers.length} (data-only ${towers.filter((t) => !t.script).length}), items ${items.length} (data-only ${items.filter((i) => !i.script).length})`);
