// Copies the curated tower and item icons (src/data/icon-map.js) from a local
// clone of https://github.com/game-icons/icons into public/icons/gi/, and
// regenerates docs/icon-credits.md.
//
//   git clone --depth 1 https://github.com/game-icons/icons.git /tmp/game-icons
//   GAME_ICONS_DIR=/tmp/game-icons npm run import:icons

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOWER_ICON_MAP, ITEM_ICON_MAP, iconAuthor } from '../src/data/icon-map.js';
import { YT_TOWERS, YT_ITEMS } from '../src/data/youtd/generated.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = process.env.GAME_ICONS_DIR;
const OUT = join(ROOT, 'public/icons/gi');
const LICENSE = 'https://creativecommons.org/licenses/by/3.0/';
const pageUrl = (key) => `https://game-icons.net/1x1/${key}.html`;

if (!SRC || !existsSync(SRC)) {
  console.error('Set GAME_ICONS_DIR to a clone of https://github.com/game-icons/icons');
  process.exit(1);
}

// Every family (keyed by its first tier's name) and every item needs an icon.
const heads = new Map();
for (const row of YT_TOWERS) if (!heads.has(row.family) || row.tier < heads.get(row.family).tier) heads.set(row.family, row);
const missing = [
  ...[...heads.values()].filter((r) => !TOWER_ICON_MAP[r.name]).map((r) => `tower family "${r.name}"`),
  ...YT_ITEMS.filter((r) => !ITEM_ICON_MAP[r.name]).map((r) => `item "${r.name}"`),
];
const unknown = Object.values({ ...TOWER_ICON_MAP, ...ITEM_ICON_MAP }).filter((k) => !existsSync(join(SRC, `${k}.svg`)));
if (missing.length || unknown.length) {
  for (const m of missing) console.error(`missing icon for ${m}`);
  for (const k of new Set(unknown)) console.error(`unknown game-icons key ${k}`);
  process.exit(1);
}

// The upstream SVGs are a white glyph on a black square; drop the square and
// fill with currentColor so CSS masks and tints them.
rmSync(OUT, { recursive: true, force: true });
const keys = [...new Set([...Object.values(TOWER_ICON_MAP), ...Object.values(ITEM_ICON_MAP)])].sort();
for (const key of keys) {
  const svg = readFileSync(join(SRC, `${key}.svg`), 'utf8')
    .replace(/<path d="M0 0h512v512H0z"\/>/, '')
    .replace(/fill="#fff"/g, 'fill="currentColor"')
    .replace('<svg ', '<svg fill="currentColor" ');
  const name = key.split('/')[1];
  const header = `<!-- "${name}" by ${iconAuthor(key)} (${pageUrl(key)}), CC BY 3.0 (${LICENSE}). Modified: background removed, recolored to currentColor. -->\n`;
  mkdirSync(join(OUT, dirname(key)), { recursive: true });
  writeFileSync(join(OUT, `${key}.svg`), header + svg);
}

// Credits table: one row per icon, listing what uses it.
const users = new Map(keys.map((k) => [k, []]));
for (const [name, k] of Object.entries(TOWER_ICON_MAP)) users.get(k).push(`${name} (tower)`);
for (const [name, k] of Object.entries(ITEM_ICON_MAP)) users.get(k).push(name);
const rows = keys.map((k) => `| ${k.split('/')[1]} | ${iconAuthor(k)} | [game-icons.net](${pageUrl(k)}) | ${users.get(k).join(', ')} |`);
writeFileSync(join(ROOT, 'docs/icon-credits.md'), `# Icon Credits

Tower and item icons in \`public/icons/gi/\` come from [game-icons.net](https://game-icons.net)
([GitHub](https://github.com/game-icons/icons)) and are licensed under
[Creative Commons Attribution 3.0 Unported (CC BY 3.0)](${LICENSE}).

Modifications: the default black square background was removed and the glyph
fill was changed to \`currentColor\` so the game can tint each icon. Each SVG
also carries its attribution in a header comment.

The icon chosen for each tower family and item is curated in
\`src/data/icon-map.js\`. This file and \`public/icons/gi/\` are generated by
\`npm run import:icons\` (see \`tools/import-icons.mjs\`); do not edit them by hand.

${keys.length} icons by ${new Set(keys.map(iconAuthor)).size} authors.

| Icon | Author | Source | Used by |
|---|---|---|---|
${rows.join('\n')}
`);
console.log(`wrote ${keys.length} icons to public/icons/gi and docs/icon-credits.md`);
