// Downloads the tower models chosen in src/data/model-map.js from Poly Pizza,
// optimizes them with gltf-transform (meshopt, textures at most 512 px WebP)
// into public/models/, and regenerates src/data/model-library.js and
// docs/model-credits.md. Only CC0 and CC-BY models are accepted.
//
//   npm run import:models

import { writeFileSync, mkdirSync, existsSync, readdirSync, rmSync, mkdtempSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { TOWER_MODEL_MAP } from '../src/data/model-map.js';
import { YT_TOWERS } from '../src/data/youtd/generated.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'public/models');
const LICENCES = { 'CC0 1.0': 'https://creativecommons.org/publicdomain/zero/1.0/', 'CC-BY 3.0': 'https://creativecommons.org/licenses/by/3.0/', 'CC-BY 4.0': 'https://creativecommons.org/licenses/by/4.0/' };
const pageUrl = (id) => `https://poly.pizza/m/${id}`;

const families = new Set(YT_TOWERS.filter((r) => r.tier === 1).map((r) => r.name));
const unknown = Object.keys(TOWER_MODEL_MAP).filter((n) => !families.has(n));
if (unknown.length) { for (const n of unknown) console.error(`no tower family starts with "${n}"`); process.exit(1); }

// Poly Pizza embeds the model record as JSON in the page.
// Retries a few times: the site rate-limits bursts of page requests.
async function modelInfo(id) {
  for (let attempt = 1; ; attempt++) {
    const html = await (await fetch(pageUrl(id), { headers: { 'User-Agent': 'Mozilla/5.0' } })).text();
    const m = html.match(/window.__SERVER_APP_STATE__ =\s*(\{.*?\})<\/script>/s);
    const model = m && JSON.parse(m[1]).initialData?.model;
    if (model?.ResourceID) return model;
    if (attempt === 4) throw new Error(`no model data for ${id}`);
    await new Promise((r) => setTimeout(r, 3000 * attempt));
  }
}

mkdirSync(OUT, { recursive: true });
const TMP = mkdtempSync(join(tmpdir(), 'youtd-models-'));
const ids = [...new Set(Object.values(TOWER_MODEL_MAP).map((v) => (typeof v === 'string' ? v : v.id)))].sort();
const library = {};
for (const id of ids) {
  const m = await modelInfo(id);
  if (!LICENCES[m.Licence]) throw new Error(`${id} "${m.Title}" has licence ${m.Licence}, which is not allowed`);
  const file = join(OUT, `${id}.glb`);
  if (!existsSync(file)) {
    const res = await fetch(`https://static.poly.pizza/${m.ResourceID}.glb`);
    if (!res.ok) throw new Error(`download failed for ${id}: ${res.status}`);
    const raw = join(TMP, `${id}.glb`);
    writeFileSync(raw, Buffer.from(await res.arrayBuffer()));
    execFileSync('npx', ['-y', '@gltf-transform/cli@4', 'optimize', raw, file, '--compress', 'meshopt', '--texture-compress', 'webp', '--texture-size', '512'], { stdio: 'ignore' });
  }
  library[id] = { title: m.Title.trim(), author: m.Creator?.Username || 'Anonymous', licence: m.Licence, tris: m.Tris, animated: !!m.Animated };
  console.log(`${id}  ${m.Licence.padEnd(9)} ${String(m.Tris).padStart(6)} tris  ${m.Title} by ${library[id].author}`);
}
rmSync(TMP, { recursive: true, force: true });
// Drop files no longer referenced by the map.
for (const f of readdirSync(OUT)) if (f.endsWith('.glb') && !library[f.slice(0, -4)]) rmSync(join(OUT, f));

writeFileSync(join(ROOT, 'src/data/model-library.js'), `// Generated by tools/import-models.mjs from src/data/model-map.js. Do not edit by hand.
// Poly Pizza model id -> metadata used for credits.

export const MODEL_LIBRARY = ${JSON.stringify(library, null, 2)};
`);

const users = new Map(ids.map((id) => [id, []]));
for (const [name, v] of Object.entries(TOWER_MODEL_MAP)) users.get(typeof v === 'string' ? v : v.id).push(name);
const rows = ids.map((id) => {
  const l = library[id];
  return `| ${l.title} | ${l.author} | [poly.pizza](${pageUrl(id)}) | [${l.licence}](${LICENCES[l.licence]}) | ${users.get(id).join(', ')} |`;
});
writeFileSync(join(ROOT, 'docs/model-credits.md'), `# Model Credits

Tower models in \`public/models/\` are downloaded from [Poly Pizza](https://poly.pizza).
Modifications: meshes are meshopt-compressed and textures resized to at most
512 px and re-encoded as WebP by gltf-transform; the models are otherwise unchanged. Each is CC0 (no attribution required, listed
anyway) or CC-BY (attribution required). Towers without an entry here use the
game's own procedural models.

The model chosen for each tower family is curated in \`src/data/model-map.js\`.
This file, \`src/data/model-library.js\` and \`public/models/\` are generated by
\`npm run import:models\` (see \`tools/import-models.mjs\`); do not edit them by hand.

${ids.length} models by ${new Set(Object.values(library).map((l) => l.author)).size} authors.

| Model | Author | Source | Licence | Used by |
|---|---|---|---|---|
${rows.join('\n')}
`);
console.log(`wrote ${ids.length} models to public/models, src/data/model-library.js and docs/model-credits.md`);
