// Text prompts for tower families that have no fitting free model, used by
// tools/import-models.mjs to generate one with Meshy (MESHY_API_KEY). Keyed by
// the family's first tier name; later tiers reuse the model at a larger scale.
// Describe the subject only: the shared style is appended by the tool.

export const MESHY_STYLE = 'Stylized low-poly fantasy game asset in the style of Warcraft III, chunky readable silhouette, '
  + 'hand-painted colors, single object centered and standing upright, no pedestal, no ground plane, no text.';

export const MESHY_PROMPTS = {
  // astral
  'Astral Rift': 'A floating tear in space framed by jagged violet crystals, swirling starry void inside, small orbiting rocks.',
  'Holy Energy': 'A floating golden orb of holy light inside three crossed gold rings, with angel-wing shaped light fins.',
  'Lesser Priest': 'A robed human priest in white and gold vestments holding a glowing staff with a sun emblem, calm pose.',
  'Library of Alexandria': 'A small ancient Greek library building with marble columns, a triangular roof and scroll shelves visible inside.',
  'Lunar Sentinel': 'A tall silver armored sentinel statue holding a crescent moon shaped glaive, pale blue glowing eyes.',
  'Magic Battery': 'A fantasy arcane battery: a brass and wood cylinder housing a glowing blue crystal core, with copper coils and runes.',
  'Nortrom the Silencer': 'A hooded night elf assassin in dark purple armor holding a curved glaive, one finger raised to his lips.',
  'Princess of Light': 'A young princess in a flowing white and gold gown with a radiant crown, holding a glowing scepter.',
  'Solar Emitter': 'An arcane device of brass rings around a blazing miniature sun, mounted on a three-legged stand, pointing upward.',
  'Warrior of Light': 'A human warrior in polished white and gold plate armor with a shining sword and round sun shield, battle-ready stance.',
  // darkness
  'Chaos Warlock': 'A sinister warlock in spiked black and crimson robes, horned skull mask, green fel fire swirling in his raised hand.',
  'Dark Battery': 'A fantasy dark battery: an iron cylinder with bone fittings housing a glowing purple shadow crystal and dark runes.',
  'Death Knight': 'An undead death knight in black spiked plate armor with a glowing blue runeblade and a tattered dark cape.',
  'Essence of Fury': 'A floating red and black spirit flame shaped like a screaming face, embers and dark smoke around it.',
  'Hall of Souls': 'A gothic undead mausoleum with green glowing windows, bone ornaments and ghostly wisps rising from the roof.',
  'Haunted Rubble': 'A pile of broken stone ruins and timber with pale green ghost lights drifting among the rubble.',
  'It': 'A shapeless shadow creature of black tar with many glowing yellow eyes and grasping tendrils rising from the ground.',
  'Lunar Emitter': 'An eerie arcane device of dark iron rings around a glowing pale crescent moon, mounted on a three-legged stand.',
  'Mister Fireflies': 'A small hunched forest spirit in a lantern hat, surrounded by a swarm of glowing yellow fireflies.',
  'Monolith of Chaos': 'A tall black obsidian monolith with cracked glowing red chaos runes and floating stone shards around it.',
  'Necromantic Altar': 'A dark stone altar with skulls, black candles, a glowing green tome and a carved bone frame.',
  'Soul Vault': 'A heavy iron and stone vault door shaped like a skull, with glowing blue souls seeping through the cracks.',
  'Soulflame Device': 'A sinister iron lantern machine with gears and pipes, burning a ghostly green soul flame in a glass chamber.',
  // fire
  'Area Roaster': 'A medieval fire-spitting brazier turret: an iron bowl of coals on a rotating stand with three flame nozzles.',
  'Ash Geyser': 'A cracked volcanic rock vent with a column of grey ash and orange embers erupting from it.',
  'Black Rock Totem': 'A carved black basalt orc totem pole with fierce faces, glowing orange lava cracks and bone decorations.',
  'Caged Fire': 'A living fire elemental trapped inside a heavy black iron cage with chains.',
  'Felweed': 'A tall twisted demonic plant with sickly green fel-glowing leaves and thorny purple stems.',
  'Fenced Flames': 'A ring of wooden stakes fencing in a roaring bonfire, iron bands around the posts.',
  'Fiery Pebble': 'A small cluster of rocks with glowing orange magma cracks and little flames licking out.',
  'Fire Battery': 'A fantasy fire battery: an iron and brass cylinder housing a glowing orange flame crystal, with heat vents and runes.',
  'Firestorm Cell': 'A glass and brass containment cell holding a swirling miniature firestorm, metal clamps and glowing runes.',
  'Geothermal Extractor': 'A dwarven steam-punk drilling rig with a drill bit, pipes, pressure gauges and lava glowing at the base.',
  'Inflamed Stone': 'A jagged standing stone with burning orange runes and flames rising from its peak.',
  'Little Phoenix': 'A young phoenix bird with blazing orange and gold feathers and a flaming tail, wings half spread.',
  'Meteor Totem': 'A carved stone totem holding a flaming meteor rock in a clawed cradle at its top.',
  'Servant of the Twin Flames': 'A robed fire acolyte holding two burning torches crossed above his head.',
  'The Furnace': 'A massive dwarven iron furnace with a glowing open mouth, chimney, bellows and coal pile.',
  'The Omnislasher': 'A muscular orc blademaster with a long curved katana, topknot hair and a flowing red sash, mid-slash pose.',
  'Vulshok, the Berserker': 'A wild berserker warrior with red war paint, fur shoulder pads and two massive axes, roaring.',
  // ice
  'Chilled Spire': 'A tall twisted spire of blue ice crystal with frost mist at its base and sharp icicles.',
  'Cold Obelisk': 'A tall pale blue stone obelisk covered in frost with glowing cyan runes and icicles hanging from it.',
  'Fisherman': 'A bearded old ice fisherman in a fur coat and hat holding a fishing rod, standing beside a small ice hole with a fish.',
  'Frost Root': 'A gnarled frozen root and vine plant growing upward, covered in ice crystals and frost.',
  'Frosty Rock': 'A craggy grey boulder covered in snow and frost with small ice crystals growing from cracks.',
  'Ice Battery': 'A fantasy ice battery: a silver cylinder housing a glowing cyan ice crystal, frost on the casing and runes.',
  'Lesser Ice Defender': 'A stocky ice golem made of blue ice blocks holding a frozen shield, glowing white eyes.',
  'Magna Warrior': 'A tall tribal ice hunter in white fur armor with a long frost spear and a bone mask.',
  'Small Ice Mine': 'A small frozen mine entrance with wooden supports, icy walls and blue crystal ore in a minecart.',
  'Snowy Pebble': 'A small pile of grey rocks topped with snow.',
  'Tidewater Stream': 'A swirling living water elemental rising from a puddle, blue translucent waves forming a column.',
  // iron
  'Abandoned Pit': 'A small abandoned mining pit with a wooden frame, rope pulley, bucket and scattered rocks.',
  'Ball Lightning Accelerator': 'A steampunk machine with a copper ring accelerator and a glowing blue ball of lightning in the center.',
  'Burrow': 'A goblin underground burrow entrance: a mound of dirt with a wooden reinforced hole and lantern.',
  'Contraption': 'A wacky goblin contraption of gears, springs, pipes and a spinning blade arm on a wooden frame.',
  'Energy Junction': 'A steampunk energy relay pylon with brass coils, insulators and glowing blue cables meeting at the top.',
  'Glaive Master': 'A night elf warden in dark armor holding a large three-bladed moon glaive overhead.',
  'Goblin Stronghold': 'A ramshackle goblin fortress tower made of scrap metal and wood, with a cannon and a green flag.',
  'Helicopter Zone': 'A goblin gyrocopter: a small steampunk helicopter with a rotor, a pilot seat and two guns.',
  'Mossy Acid Sprayer': 'A mossy iron tank on legs with a nozzle spraying green acid, dripping pipes and valves.',
  'Particle Accelerator': 'A steampunk particle accelerator: a ring of brass magnets with a glowing energy stream circling inside.',
  'Sewer Connection': 'A rusty sewer pipe junction rising from the ground with valves, a manhole cover and green ooze leaking.',
  'Silver Knight': 'A noble knight in shining silver plate armor holding a lance and a kite shield with a lion crest.',
  'Sniper': 'A dwarven rifleman crouching with a long-barreled hunting rifle and a scope, wearing a horned helmet.',
  'The Steam Engine': 'A small steampunk steam engine with a boiler, chimney, pistons and a spinning flywheel.',
  'Valor': 'A heroic paladin in gold-trimmed blue plate armor raising a warhammer, a blue cape flowing.',
  // nature
  'Afflicted Obelisk': 'A moss-covered stone obelisk corrupted by purple blight, thorny vines and sickly glowing spores.',
  'Inexperienced Huntress': 'A young night elf huntress in leather armor with a bow, a quiver and a small owl on her shoulder.',
  'Lesser Natural Defender': 'A small treant made of bark and leaves with a wooden shield and glowing green eyes.',
  'Morphling': 'A shapeshifting water creature, a humanoid made of flowing blue liquid with a glowing core.',
  'Mud Golem': 'A hulking golem made of brown mud and stones, grass and roots growing from its shoulders.',
  'Nature Sprites': 'Three tiny glowing green forest fairies with leaf wings dancing around a flower.',
  'Poison Battery': 'A fantasy poison battery: a wooden and copper cylinder housing a glowing green toxic crystal, dripping venom.',
  'Rooted Chasm': 'A cracked earth chasm with thick roots and blooming flowers spilling out of the crevice.',
  // storm
  'Ancient Energy Converter': 'An ancient stone and bronze machine with spinning rings and a crackling blue energy core.',
  'Arcane Storm': 'A small swirling purple storm cloud with arcane lightning bolts, floating above a runed stone disc.',
  'Broken Lightning Rod': 'A tall bent iron lightning rod on a stone base, sparks crackling at its tip.',
  'Chaining Storm': 'A floating dark storm cloud with chains of lightning arcing down from it.',
  'Cloud Warrior': 'A warrior made of white storm clouds with a lightning spear, a crackling blue core in his chest.',
  'Dimensional Flux Collector': 'An arcane device of floating rings around a shimmering purple portal sphere on a tripod.',
  'Gnoll Thunder Mage': 'A hyena-headed gnoll shaman in tattered robes holding a staff crackling with lightning.',
  'Green Lightning': 'A jagged crystal pillar crackling with green lightning bolts.',
  'Lightning Eye': 'A giant floating eyeball wrapped in metal bands, crackling with blue lightning.',
  'Lightning Generator': 'A dwarven lightning generator machine with copper coils, a crank and sparking electrodes.',
  'Lightning Totem': 'A carved wooden tauren totem pole topped with eagle wings, blue lightning crackling around it.',
  'Red Ball Lightning': 'A floating ball of red lightning held in a bronze claw on a short pole.',
  'Ruined Monolith': 'A broken ancient stone monolith with faint glowing blue storm runes.',
  'Ruined Storm Cap': 'A ruined stone column capped with a cracked metal dome, sparks of lightning leaking out.',
  'Scales': 'A large golden balance scale with two pans, one glowing with lightning and one with arcane light.',
  'Spell Collector': 'An arcane bronze funnel device collecting swirling magic runes into a glass orb.',
  'Storm Battery': 'A fantasy storm battery: a bronze cylinder housing a crackling blue lightning crystal, with coils and runes.',
  'Storm Coil': 'A tall tesla coil tower of copper rings on a stone base with blue lightning arcing from the top sphere.',
  'Storm Focus': 'A floating storm crystal held between three bronze prongs, lightning focused into a beam.',
  'The Conduit': 'A tall arcane conduit pylon of stone and metal with glowing energy lines running up to a floating crystal.',
};
